### ISSUE TITLE
Line 5 of _keyboard.scss: Invalid US-ASCII character "\xC3"

### ISSUE THREAD

**Issue by Cinamonas** [MoOx/compass-recipes#100]
After updating Ruby (it's `ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]` on OS X Mavericks), [this](https://github.com/MoOx/compass-recipes/blob/master/stylesheets/recipes/ui/_keyboard.scss#L5) line breaks compilation.

**Comment by MoOx** [comment]
I'm guessing it's the `ü`. So weird that this line is causing issue.
Can this be related to your current file encoding ?

**Comment by Cinamonas** [comment]
I've just tried this with other stylesheets I haven't touched for quite some time. They use `compass-recipes`, they did work before, but now they fail with the same error.

Could this be related to updated Ruby?

**Comment by MoOx** [comment]
Yep, or an OS update. It seems files has been parsed has ascii/iso, non utf8 like they should.
No idea how to handle that.
Are you using command lines ? If yes, check the env variable ([more here ?](http://stackoverflow.com/questions/5306153/how-to-get-terminals-character-encoding))

**Comment by MoOx** [comment]
So @Cinamonas did you fix your problem ?

**Comment by Cinamonas** [comment]
Yeah, with a quick and dirty workaround -- changing that UTF-8 char to ASCII :)

**Comment by MoOx** [comment]
--'

**Comment by ofi** [comment]
Ha, this made it work without monkey-patching:

``` bash
$ export LC_CTYPE="de_DE.UTF-8" # in my case
$ export LANG="de_DE.UTF-8"
$ compass compile # no errors anymore
```

The funny thing is: After unsetting both variables it kept working, I guess because of SASS cacheing somewhere.
Please don't praise me for this; I was inspired by: http://stackoverflow.com/questions/4917859/ruby-error-utf-8-to-ascii

**Comment by MoOx** [comment]
Thanks for sharing this solution.

**Comment by Luckyfella73** [comment]
I had the same problem and was able to fix it by just putting this into the first(!) line of my .scss files:

```
@charset "utf-8";
```

Found it in the docs, saying:

> To explicitly specify the encoding of your stylesheet, use a @charset declaration just like in CSS.
> Add @charset "encoding-name"; at the beginning of the stylesheet (before any whitespace or
> comments) and Sass will interpret it as the given encoding. Note that whatever encoding you use,
> it must be convertible to Unicode.
