### ISSUE TITLE
Trying to use corners-tucked with background-noise

### ISSUE THREAD

**Issue by MikeAdamowicz** [MoOx/compass-recipes#104]
Hi,
Quite new to github, so if this is an inappropriate way to ask about this, please forgive me and inform me of the proper method.

I am using background-noise, which is a large data:image/png;base64. And I want to use recipes/effect/corners-tucked. 

This yields a disparity between the tucking corners and the background. See:
![before](https://f.cloud.github.com/assets/6062455/1818388/998d7a06-6ffe-11e3-9091-d7d109ba95d8.jpg)

I was trying to avoid repeating the lengthy background-image: (url)('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAM...
Searched the web and didn't find anything helpful. 

So, I thought to take a small snippet and write: background-image: url(images/snippet.jpg)  background-repeat:repeat.  But that led to a see-through problem. See:
![tucked](https://f.cloud.github.com/assets/6062455/1818396/788a39ce-6fff-11e3-9ab0-080a2edc2784.jpg)

At first, I played with z-index and put a z-index at various numbers all the way up to 9999 for  .tucked-corners:after, .tucked-corners:before... 
Gave .tucked-corners ever-decreasing z-index values...  
No changes.  Remained see-through.

I bit the bullet and did background-image: url('data:image/png;base64,iVBORw0KGgo...
But there was remarkably little change, even after going through all the z-index trials again.  See:
![third](https://f.cloud.github.com/assets/6062455/1818406/bd8213e8-7000-11e3-9f1c-28040ead21e2.jpg)

So I'm not sure if this is a problem that is due to my limitations or if there is a conflict between the two mixins.

Again, if this is not the appropriate forum for this, my apologies for imposing on your time.

Mike Adamowicz

**Comment by MoOx** [comment]
Sure it's not a forum here, but it's an interesting problem.
Can you share the minimal code to reproduce the issue please ?

**Comment by MikeAdamowicz** [comment]
I made a page of 4 examples to show the problem. I am now thinking that the issue is that tucked-corners will only allow hex values for background. But that is an amateur's guess.
Here's the URL:
http://ri-website-designers.com/compass/recipe/tucked_corners.html

**Comment by MoOx** [comment]
Don't just use `background-image:`. I just try to use `background: red url(whatever)`, and this give me that (for jpg & noise)

![screen shot 2013-12-29 at 14 28 46](https://f.cloud.github.com/assets/157534/1819405/32eca74c-708d-11e3-9527-2ae0a3752e77.png)

You will just need to adjust the right color for the noise.

Note: for the first example using the jpg, the image give 404.
Note 2: Just don't `@import "compass"` nor `@import "recipes"` if you import just specific part below. Making that import all (not good for perf) & reimport specific part after (double import...).

**Comment by MikeAdamowicz** [comment]
Hi,
Thanks for your speedy reply to this. It's very much appreciated, as are your kind suggestions in Note 2!!
Best wishes for the New Year,
MikeAdamowicz
