### ISSUE TITLE
Add lots of animations

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#17]
Take inspiration from here https://github.com/daneden/animate.css
- http://fvsch.com/code/transition-fade/

**Comment by theCSSguru** [comment]
Just Created an Animate Mixin for Compass/SASS! It's based on work done here by Animate.css, check it out! http://thecssguru.freeiz.com/animate/

**Comment by MoOx** [comment]
Would you like to push you work into this repo ?

**Comment by MoOx** [comment]
We could use keyframes syntaxes available in sass 3.2 (actually pre version)

https://gist.github.com/1215856 ( thanks @chriseppstein )

**Comment by MoOx** [comment]
Memo: https://github.com/daneden/animate.css/tree/master/source

Keyframes mixin is working (not commited), just need to add example to make it "viewable" :)

**Comment by MoOx** [comment]
Create example like this http://tympanus.net/Tutorials/OriginalHoverEffects and this http://tympanus.net/Tutorials/CreativeCSS3AnimationMenus/

**Comment by MoOx** [comment]
There is already enough compass extension for that (ceaser-easing is simple but flexible)
