### ISSUE TITLE
Add CSS patterns

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#2]
Add all patterns mixins from @LeaVerou's patterns Gallery 
http://leaverou.me/css3patterns
Code: https://github.com/LeaVerou/CSS3-Patterns-Gallery/blob/master/index.html

**Comment by MoOx** [comment]
This is nice too http://simurai.com/post/9214147117/css3-brushed-metal

**Comment by MoOx** [comment]
2 new added 1900201940e997acb69a0cf56c91fa1d7827b776

**Comment by MoOx** [comment]
What about this animated backgrounds by the awesome @simurai ? 

http://lab.simurai.com/css/space-cacss/

**Comment by simurai** [comment]
Sure go ahead. Using SASS would make a lot of sense. It should make it even easier to create those patterns than hacking everything by hand. But in case of the Space CaCSS.. not sure if it would be THAT useful in the real world.. hehe.. they're more like web toys. ;-)

Something I'm thinking of doing that would be more useful. Pixel patterns or subtable background patterns like http://subtlepatterns.com/ but with CSS instead of an image.

**Comment by MoOx** [comment]
Thanks for your comment.
You're right. But I like web toys :)
My job is to play with CSS !

I've already think about adding subltepatterns. It'll be awesome to have most of them.
Today, they have "124 patterns".  This count make me freak out about the implementation ^^
But why not ? :)

**Comment by simurai** [comment]
Hehe.. yeah.. well, it doesn't have to be a 1:1 copy.. probably not really possible. But just a couple in that style.

**Comment by knoopx** [comment]
merge?

**Comment by MoOx** [comment]
Merge what ?

**Comment by knoopx** [comment]
sorry I meant "can you push this to ruby gems?"
the latest ruby gem does not include all the background pattern goodness

**Comment by knoopx** [comment]
also I misinterpreted that all http://lea.verou.me/css3patterns/ patterns were already implemented

**Comment by MoOx** [comment]
There is a lot of work to do but anyway, I try to will push the work done this weekend as a --pre, so stay tuned.

**Comment by MoOx** [comment]
For now the available backgrounds patterns are available in the gem using --pre
https://rubygems.org/gems/compass-recipes/versions/0.3.0.alpha.1
New backgrounds are visible here http://moox.github.com/compass-recipes/recipes/background/
@canarymason add some of the new ones.
(sorry if demo are without style for now, I will make something prettier soon)

**Comment by codingdesigner** [comment]
Thanks for the nudge. I do need to get back to those. :)

**Comment by MoOx** [comment]
Goto #71
