### ISSUE TITLE
Gravatar helper

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#27]
Create gravatar function (to generate gravatar url) using Digest::MD5

`http://www.gravatar.com/avatar/" + MD5 $email + "&s=" $width`

Eventually make an helper based on a html data-email attribute (+ data-avatar-width ?), and use a pseudo element to add the gravatar ?

Do you think it's a good idea ?

JS Source: http://darcyclarke.me/development/quick-tip-get-gravatar-images-from-emails-with-javascript

**Comment by davidkaneda** [comment]
I think it's a fantastic idea — only lame thing (and it's the same with Clarke's) is that you have to have people's email available in plaintext. But if you're ok with that, it's pretty great. Maybe we make it easy to substitute the (@) character with something else for some slight protection.

**Comment by MoOx** [comment]
We cannot compute md5 of the email in css, only with ruby or js, so there is to use case:
- you have a plain text email in your sass file (not a problem) to compute the md5 & generate the url
- you have a m5d in the html like data-email-md5="..." & the css use directly the md5 with something like `content: "http://www.gravatar.com/avatar/" attr(data-email-md5) "&s=100"`
  In the second case, the md5 can be computed in javascript using the technique in the link. & we can also compute mdf5 from a simply encoded email (like `stuff [ at ] domain [ dot ] tld`)

**Comment by MoOx** [comment]
An idea about where to place this recipes ?

ui/helper/gravatar ?
helper/gravatar ?
misc/gravatar ?

**Comment by MoOx** [comment]
It's impossible without javascript for now (see http://dabblet.com/gist/1901062)
Maybe I will try to create a javascript. But maybe javascript does not have to be in there ?
I'll give a try to add a layer of behavior.
