### ISSUE TITLE
Fix webfont tests for showcase

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#30]
This does not work.
http://moox.github.com/compass-recipes/recipes/ui/webfont-icons/
It have to :)

We have to find a way to move font during building gh-pages. Using a var for the location or something like that.

**Comment by davidkaneda** [comment]
How are you building the gh-pages? Looks like tests/recipes is just being duped up one level into recipes. Are you using an ant task or something? Can you commit it in if so? Why not just link to the tests/recipes from the index.html?

**Comment by MoOx** [comment]
The script is in the rakefile.
I just copy and adapt the script from sass-recipes.
You have to call 'bundle exec rake pages'.
It prepends a footer (ga script).

Max

(Sent from my phone)
