### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by Snugug** [MoOx/compass-recipes#38]
Used the "Additional Path" Compass trick to use the current head of Compass Recipes, and when I @import "recipes";, the following Compass error occours:

Line 1: File to import not found or unreadable: recipes/form/element/border-color.

This is obviously preventing me from using all of Compass Recipes. If you have a quick fix for me to do that would be great, but it does need to be resoled.

**Comment by MoOx** [comment]
Have you replace compass-recipes stable with the current head ? If yes, do you use `@import "recipes/form/element/border-color"` ?
Because this recipe have been removed, & there is no trace of "element/border-color" in all files in the current head.

Are you sure the `@import "recipes";` add the error ? (I've just try to import all & I've no error)

**Comment by Snugug** [comment]
Yes, I just did a fresh clone into Compass Recipes, @import "recipes", and getting that error.

**Comment by MoOx** [comment]
I just did the same on a fresh zip download
http://cl.ly/1F2c3k1X3R3u230B0023
http://cl.ly/1K3l3X2K1v0v3F3O392p
No problem.

So I guess the "old" stable gem I making the problem. `@import "recipes";` include the stable gem...
First thing, to correct the gem bug: (my path assume you are on OSX).
Remove the first line of the file /Library/Ruby/Gems/1.8/gems/compass-recipes-0.2.0/stylesheets/recipes/form/_element.scss.
You will no longer have the error.

But it's weird that the "additional path" have not a higher priority on the gems...
I will take a look...

**Comment by MoOx** [comment]
Or maybe just remove the compass-recipes 0.2 gem :)

**Comment by Snugug** [comment]
Removed the compass-recipes 0.2 gem, but now my config.rb isn't picking up the additional paths:

in config.rb:

```
# Additional Import Paths
additional_import_paths = '~/Development/compass-recipes/stylesheets'

# Require any additional compass plugins here.
require 'compass-recipes'
```

Now it's throwing:

```
LoadError on line 31 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb: no such file to load -- compass-recipes
```

Am I using additional_import_paths wrong?

BTW, thank you for your help.

**Comment by MoOx** [comment]
Yes you are using it wrong :p

`additional_import_paths` - _Array of Strings_ - Other paths on your system from which to import sass files. See the add_import_path function for a simpler approach.

So you need

```
additional_import_paths = [
    '~/Development/compass-recipes/stylesheets'
]
```

Maybe you just want :
    add_import_path "~/Development/compass-recipes/stylesheets"

from http://compass-style.org/help/tutorials/configuration-reference/

**Comment by Snugug** [comment]
Ahh, Ruby array, not Sass array. Either way, still not working; same error. Now using add_import_path

**Comment by MoOx** [comment]
I found this in my memory http://groups.google.com/group/compass-users/browse_thread/thread/8e655d6706ca6d2d?pli=1
Maybe using ~/ unix trick does not work (since the ruby process does not know your homepath ?)
Is it working with add_import_path ?

**Comment by Snugug** [comment]
It's not working w/add_import_path and I tried changing to an absolute directory, neither of which did the trick.
Is there a reason the gem isn't updated? Can I help w/that? Can I compile a gem out of the git repo?

**Comment by MoOx** [comment]
It's weird for the import path. I used to import recipes like that...
Do you use `compass watch`or Compass.app ?

We have planned to release an alpha release (but @davidkaneda have to push something before)

Anyway, you can build the gem easily (everything is almost ready).
Into the repo:

```
sudo gem build compass-recipes.gemspec
sudo gem install compass-recipes-0{tab}
```

This should works.

**Comment by Snugug** [comment]
Compass Watch

So when running gem build, got the following:
```ERROR:  While executing gem ... (NoMethodError)
    undefined method`today' for Date:Class

```
```

**Comment by MoOx** [comment]
Hum (I'm not a ruby pro, so I do not know where the Date class is...)...
So just edit the gemspec file & remove the date line. It should works.

**Comment by Snugug** [comment]
That worked. Thank you very much!

**Comment by MoOx** [comment]
I understand where was [the problem](https://github.com/MoOx/compass-recipes/issues/38#issuecomment-3653021) with your import.

You use additional path & `require 'compass-recipes'`.
require is for require a gem, so your error was normal.

I have to take some times to make a doc for this.

**Comment by Snugug** [comment]
Sounds good, thanks for figuring that out.

**Comment by MoOx** [comment]
[Here is a good start](/MoOx/compass-recipes/wiki) :)

**Comment by MoOx** [comment]
0.2.1 has been released on rubygems to fix this.
