### ISSUE TITLE
updated gem

### ISSUE THREAD

**Issue by codingdesigner** [MoOx/compass-recipes#44]
What features are standing in the way of building an updated gem? I'm using CR currently and a released gem would help me share my work with other devs here. I'm willing to help.

**Comment by MoOx** [comment]
I've plan to create different branch for both stable & development state to be able to quickly propose stable & --pre gem.

I will release an alpha for the 0.3 tonight or tomorrow morning

**Comment by MoOx** [comment]
Btw, you can checkout what is missing to release the 0.3 using filter on the issues :)

https://github.com/MoOx/compass-recipes/issues?sort=created&direction=desc&state=open&page=1&milestone=2

**Comment by codingdesigner** [comment]
:) I'm a little hasty with the issue. I have a couple things I'm planning to submit soon, btw.

**Comment by MoOx** [comment]
Done ! https://rubygems.org/gems/compass-recipes/versions/0.3.0.alpha.1

**Comment by codingdesigner** [comment]
yay!

**Comment by MoOx** [comment]
I'm confortable with gem now. I will push more often.
