### ISSUE TITLE
Problem with the gem 0.3.0.alpha.1

### ISSUE THREAD

**Issue by Anahkiasen** [MoOx/compass-recipes#45]
I'm trying to use Compass-Recipes as a gem. I got the --pre version but when I want to do anything it throws an error "Unable to find "recipes/webfont-icon"". And indeed when I go into the gem folder and look at the root _recipes.scss file, it looks like most of the paths are from another CR version and don't match the recipes/ subfolder. Is this normal ?

**Comment by MoOx** [comment]
I know that. Sorry but I always forget to update this file. I've to make a better process before pushing a gel.
I will push a new alpha release today or tomorrow.

**Comment by Anahkiasen** [comment]
Well nevermind, I just did a checkout of the Git inside the gem folder, works fine.

**Comment by MoOx** [comment]
:)
