### ISSUE TITLE
Change comments syntax

### ISSUE THREAD

**Issue by Anahkiasen** [MoOx/compass-recipes#46]
According to the SASS documentation, `/* */` is for CSS comments, and // for SASS comments. Thing is, most of the comments in CR are the former and thus output about 600 lines of comments in the final .css in the non-compressed modes of SASS.
According to Sass recommendations, a sass class should output absolutely _nothing_ when being imported.

**Comment by MoOx** [comment]
Yeah I know that. I came from php world, & I use to make /\* */ doc, but it's pretty a bad thing with sass. We have to change this before releasing 0.3. @canarymason told me we have planned to update the comment style. I will check this & update asap.

**Comment by Anahkiasen** [comment]
In the meantime I asked the SASS developper to include a `hide-comment` flag for comments. We'll see.

**Comment by codingdesigner** [comment]
I got busy and had to put it aside for some client work and a trip. I may have time to tackle this today tho. I'll let you know.

**Comment by MoOx** [comment]
Great. Thanks.

**Comment by MoOx** [comment]
Closed with 2fd3744436110814bef2138cfd6b670d71ebb4e7
