### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by gasatrya** [MoOx/compass-recipes#49]
I got this

<pre>Syntax error: File to import not found or unreadable: recipes/form/skin/default</pre>

I don't know what happen here, I don't find any code called the `recipes/form/skin/default`

**Comment by gasatrya** [comment]
Just updated to 0.3.0.alpha.2, and everything looks awesome!

Thanks

**Comment by MoOx** [comment]
Are you using `@import "recipes"` ? 
Which version ?

## 

Maxime Thirouin

**Comment by gasatrya** [comment]
Yes of course, First I installed 0.2.1, but i got the error like above, then I updated to 0.3.0.alpha.2. I'm using compass 0.12.2.rc.0
