### ISSUE TITLE
Add automatic behavior to manage HiDPI background images

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#63]
https://gist.github.com/2140082

http://miekd.com/articles/using-css-sprites-to-optimize-your-website-for-retina-displays/
http://blog.waymondo.com/2012-11-09-automagic-retina-sprites-with-compass-and-sass/
http://www.gayadesign.com/diy/retina-sprites-for-compass/

**Comment by msadouni** [comment]
this may help too : http://www.gayadesign.com/diy/retina-sprites-for-compass/

**Comment by MoOx** [comment]
Interesting indeed. Thanks :)

**Comment by MoOx** [comment]
Ping @kaelig with his https://github.com/kaelig/hidpi.
Maybe I should just make some PR to hidpi project directly & use it has a dep.
Hum since this will require some ruby, I'll see.
