### ISSUE TITLE
Normalize whitespace & code convention

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#84]
Whitespace should use tab only (less bytes) & css block should be like this

``` scss
selector,
selector 2 {

}
```

not like this

``` scss
selector,
selector 2
{

}
```

No ?

**Comment by kaelig** [comment]
I'd recommend 2 spaces for indentation when in a full-Sass/SCSS workflow. The output is 2 spaces anyway, which makes it easier to copy-paste snippets between output/source.

**Comment by MoOx** [comment]
I like @necolas [advices on whitespaces in idiomatic CSS](https://github.com/necolas/idiomatic-css#2-whitespace)
I find 2 spaces hard to read. I prefer 4 spaces indentation too, using tab since it use less bytes (it's my green side :) )

**Comment by kaelig** [comment]
Well, since your output is going to be minified, just chose what you like best and are most comfortable with.

In a Sass workflow it's clear that 2 spaces make more sense (Haml, Ruby and Sass are built with meaningful 2-space indentation).

**Comment by MoOx** [comment]
You're right, maybe I'll just use 2 spaces for this project.

**Comment by MoOx** [comment]
Must use .editorconfig (http://editorconfig.org)
