### ISSUE TITLE
Font icons does not work on gh-pages

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#85]
Symbolic link does not work on github pages.

Btw, should I publish the website on another domain?

**Comment by krisbulman** [comment]
Font-icons definitely can work on gh-pages: http://krisbulman.github.com/font-icons/ 

but they are not working in your tests 

http://moox.github.com/compass-recipes/tests/recipes/icon-font/

**Comment by MoOx** [comment]
Thanks for the comment. But it's about a sym link issue. Not about webfont

**Comment by MoOx** [comment]
Because of the symlink, it cannot work. Anyway, there is a new website url where this work: http://compass-recipes.moox.fr/

**Comment by krisbulman** [comment]
Still don't see the fonts? https://skitch.com/krisbulman/eir6j/mozilla-firefox

**Comment by MoOx** [comment]
Oh, I forgot to said, my webpage is kind of dum. It output a lot of unicode, too much. Some icon fonts just use a few. You should see some icons for each fonts at least.

**Comment by MoOx** [comment]
It's a javascript which render some unicode from X to Y.
