### ISSUE TITLE
Add lots of buttons

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#9]
The main idea is to add minimal recipes to be able to create a high range of buttons.
So we do not need mixin like button-github-blue or button-orange-with-noise.
I think with less than 10 mixins, we can create tons of examples.
Or maybe 3 or 4 mixins will be enough.

Inspiration
http://lab.simurai.com/css/buttons/
http://brandonmathis.com/projects/fancy-buttons/demo/
http://dribbble.com/shots/544622-Blankslate
https://github.com/jhardy/Sassy-Buttons

For examples: 
http://houseofbuttons.tumblr.com/
http://forrst.com/posts/CSS_Button_Contest-5J1

Trick for 1px border on retina:
http://bradbirdsall.com/mobile-web-in-high-resolution
http://codepen.io/pen/bKens

**Comment by MoOx** [comment]
Animation on 3d button: http://nicolasgallagher.com/lab/css3-animated-button/

**Comment by olivierlacan** [comment]
Here's [my take](https://github.com/MoOx/compass-recipes/pull/12) on this. Think the section can be expanded easily with different button styles. 

I'd love input on how to improve the cleverButton mixin. For instance I'm not satisfied with the way it handles text on a light background for now. There should be a point where (unless otherwise specified), the button text goes to black if the background is too light and vice versa.

**Comment by MoOx** [comment]
Here are some ideas for the result: http://ubuwaits.github.com/css3-buttons/
The goal is to be able to create a large panel of buttons using minimal code.

**Comment by MoOx** [comment]
Maybe we can use the work of @adamstac ?

https://github.com/adamstac/zocial

**Comment by adamstac** [comment]
I love what you guys are going with the recipes, but I'd prefer that Zocial remain stand alone. Unless I mis-understood.

**Comment by MoOx** [comment]
You missunderstood :)

I just want to take some code base for the button mixins ! Use it as "inspiration" ! :)

https://github.com/adamstac/zocial/blob/master/stylesheets/partials/_base.sass

**Comment by davidkaneda** [comment]
@Moox I think we should have a "button," but probably not the array of buttons shown in all of those examples, nor any from an existing framework. I'll throw together a quick recommendation and we can go from there-

**Comment by MoOx** [comment]
The goal of the button mixin, is not to have hundreds of button predefined.
All I want to do is to be able to call a button like button($theme: themename, $radius: 1em, $color: blue)

Each button theme would have options to be able to easily create examples linked.

The examples shown is the achivement to unlock when we have written a solid button mixin, with many themes availables.

I was working on this, and I encounter a problem for the theme management. I want infinite themes, but for now there is a sass restriction to make what I think about.

/see http://groups.google.com/group/compass-users/browse_thread/thread/90ac47c3f6dbdaeb

So I will finish what I've started but with limited theme :(

**Comment by davidkaneda** [comment]
Here's a sample of what I did: http://cl.ly/CPfP. Instead of theme, it gives the ability to switch background gradients with sensible defaults.

**Comment by davidkaneda** [comment]
Ideally, instead of theme, we could let them pass in an array like @include button($effects: emboss, $base-color: green, $base-gradient: matte)

**Comment by MoOx** [comment]
I will try to push what I did as soon as it's finished.
Maybe what you have done could be a... 'ui-simple-button' ? :)

**Comment by MoOx** [comment]
Maybe this extension is enough http://jaredhardy.com/sassy-buttons/
I've to just add this to the gem requirement
