### ISSUE TITLE
EXPLODE ALL THIS REPO INTO SEVERAL PIECES

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#92]
All in one it's not really the best idea.
Since a lot of code is coming, I should probably explode this into several components, so several repos.

**Comment by MoOx** [comment]
USING FONZIE https://github.com/fonzie/fonzie

**Comment by MoOx** [comment]
This is work in progress. Checkout my sass-\* repositories.

**Comment by MoOx** [comment]
Okay, it's here https://github.com/css-recipes
No more prefix, no more fancy packager.
Just Sass recipes (with optional output for non sass user use when it's possible)

**Comment by martinbavio** [comment]
So Compass recipes is no longer being mantained? I kind of like having all in just one gem.

**Comment by MoOx** [comment]
I've planned to make a `css-recipes` package that will have all other as dep, so should be the same if you use bower. Do you use it ?
I also eventually can do a gem based on this packages. Should not be a big deal.
CSS Recipes is WIP for now.

I'll not add any stuff to Compass Recipes, but I'll fix issues if there is.
I'll try to make a nice transition for everybody ;)
