### ISSUE TITLE
SVG with PNG fallback

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#97]
http://germanforblack.com/post/43975575422/protip-all-browsers-that-support-svg-background-images

**Comment by philwareham** [comment]
That method is way too risky to use in production. Modernizr tests for SVG support so leave it to that.

**Comment by MoOx** [comment]
It will just be a mixin, you can use it or not :)
Modernizr is a nice tool, but I never use it, no need for me. Fallback are fine for me when they exists.

**Comment by MoOx** [comment]
But yeah it seems risky (Just saw the updates)
