### ISSUE TITLE
transform-orgin with bourbon

### ISSUE THREAD

**Issue by davidsoderberg** [MoOx/compass-recipes#99]
Hi,

When i use the recepies with bourbon. 
I get an error on alla transform-orgin css. 
How can I solve it?

Many thanks/
David

**Comment by MoOx** [comment]
What recipe is causing the error ?
Compass Recipes has not been adjusted to work with Bourbon.
However I'm porting each recipes as standalone micro components here https://github.com/css-recipes
I'm interested to know what recipe you need so maybe I can port it to plain Sass ?

**Comment by davidsoderberg** [comment]
It is effect/ribbon that causing the error.

Thanks for quick replay :)

**Comment by MoOx** [comment]
reply*

You can try this https://github.com/css-recipes/corner-ribbon !

**Comment by davidsoderberg** [comment]
Ok, thanks that did it :)
